# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Amazon-Bezos
version:      0.001
version_from: lib/Amazon/Bezos.pm
installdirs:  site
requires:
    Amazon::S3:                    0.44
    Amazon::SQS::Simple:           0.7
    Class::ErrorHandler:           0
    File::HomeDir:                 0
    File::Spec:                    0
    Net::Amazon::EC2:              0.06
    Net::Amazon::EC2::Metadata:    0.1
    Object::Tiny:                  0
    Test::More:                    0
    YAML::Tiny:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
